extends SceneTree
var failures:=0
func _initialize()->void:run.call_deferred()
func check(ok:bool,message:String)->void:
	print(("PASS " if ok else "FAIL ")+message)
	if not ok:failures+=1
func wait(t:=.12)->void:await create_timer(t).timeout
func capture(name:String)->void:
	if DisplayServer.get_name()=="headless":return
	await wait(.15);await RenderingServer.frame_post_draw
	root.get_texture().get_image().save_png(ProjectSettings.globalize_path("res://build/gate24_"+name+".png"))
func run()->void:
	var main:Node=load("res://scenes/main.tscn").instantiate();root.add_child(main);main.port_edit.value=24764;main._host();main._start_match()
	var w:FortWorld=main.world;var p:=w.local_player();w.set_process(false);p.set_physics_process(false)
	w.set_hearth_level(3);w.shared={"wood":1000,"stone":1000,"iron":1000,"crystal":1000,"aether":1000}
	for id in w.enemies.keys():w.recv_enemy_dead(id)
	var location:=Vector3(0,.6,9.5);p.position=Vector3(0,.6,13)
	check(FortPlacement.snap(w,"Gatehouse",Vector3(.5,.6,10),0)==location,"gate snaps to castle entrance center")
	check(w.build_block_reason("Gatehouse",location,0)=="","aligned gate is allowed in marked castle entrance")
	check(w.build_block_reason("Gatehouse",location,PI/2)!="","sideways gate cannot obstruct marked castle entrance")
	check(w.build_block_reason("MetalWall",location,0)!="","ordinary walls still preserve castle entrances")
	w._build(1,{"kind":"Gatehouse","pos":location,"rotation":0.0})
	check(w.defenses.has(1),"shared supplies reserve a real gatehouse blueprint")
	if not w.defenses.has(1):main.queue_free();await wait();quit(1);return
	var d:Dictionary=w.defenses[1];var door:StaticBody3D=d.node.get_node("GateDoor")
	check(w.shared.wood==960 and w.shared.stone==936 and w.shared.iron==982,"gatehouse cost charged once from shared stockpile")
	check(FortConstruction.foundation(d) and d.node.has_node("Worksite") and door.collision_layer==0,"authored foundation is nonblocking")
	p.camera.reparent(w);p.camera.global_position=Vector3(9,7.5,22);p.camera.look_at(location+Vector3.UP*2.4);p.camera.current=true
	await capture("foundation_game")
	for stroke in 8:w.clock+=.8;w.construction.work(1,1)
	check(not FortConstruction.pending(d) and d.hp==1200 and d.paid.wood==40,"cooperative hammer work completes gate without a second charge")
	check(door.collision_layer==0 and FortGates.passable(d),"newly finished gate starts open")
	var parts:Dictionary=d.node.get_meta("gate_parts")
	check(parts.Portcullis.position.y>3 and not parts.tier2.visible,"moving portcullis raised and higher-tier art hidden at level one")
	check(d.node.find_child("Cube",true,false)==null,"export contains no default Blender cube")
	await wait()
	check(FortNavigation.clear(w,location+Vector3.BACK*2,location+Vector3.FORWARD*2),"open gate provides body-width collision-free passage")
	await capture("open_game")
	p.position=location;w.clock+=1;w.gates.request(1,1,0)
	check(float(d.get("gate_target",1))==1 and d.gate_blocked,"occupied close request refused")
	p.health=0;check(w.gates.occupied(d),"downed dwarf still protects the passage");p.health=p.max_health
	p.position=location+Vector3.BACK*3.4;w.clock+=1;w.gates.request(1,1,0)
	check(d.gate_target==0 and d.gate_revision==1,"clear passage accepts revision-checked close")
	w.gates.tick(.7)
	check(d.gate_open>0 and d.gate_open<1 and parts.Portcullis.position.y<3.15 and door.collision_layer==0,"portcullis and counterweights animate before solid closure")
	p.position=location;w.gates.tick(.1)
	check(d.gate_target==1 and d.gate_blocked,"entering a descending gate reverses it without crushing")
	p.position=location+Vector3.BACK*3.4;w.gates.tick(4);w.clock+=1;w.gates.request(1,1,d.gate_revision);w.gates.tick(4);await wait()
	check(d.gate_open==0 and door.collision_layer==1,"fully closed gate blocks collision")
	check(not FortNavigation.clear(w,location+Vector3.BACK*2,location+Vector3.FORWARD*2),"closed passage blocks a dwarf-width route")
	await capture("closed_game")
	var revision:int=d.gate_revision;w.clock+=1;w.gates.request(1,1,revision-1)
	check(d.gate_revision==revision and d.gate_target==0,"stale concurrent gate commands cannot flip it again")
	w._interact(1,true);check(d.gate_target==0,"holding E cannot repeatedly toggle the gate")
	w.clock+=1;w.player_interact(p);w.gates.tick(4);check(d.gate_target==1,"a fresh E press opens gate")
	w.clock+=1;w.gates.request(1,1,d.gate_revision,true);w.is_night=true;w.wave=1;w.gates.tick(4)
	check(d.gate_open==0 and d.gate_auto,"opt-in dusk auto-close uses the same mechanism")
	w.clock+=1;w.gates.request(1,1,d.gate_revision);w.gates.tick(4)
	check(d.gate_open==1,"manual opening overrides auto-close for the current night")
	w.recv_enemy(24001,"Raider",location,100);check(w.gates.occupied(d),"enemy in passage also prevents closure");w.recv_enemy_dead(24001)
	w.pets._create(24001,0,location) # Uses the same capsule-clearance safety as dwarves.
	check(w.gates.occupied(d),"gather pet in passage prevents closure")
	w.pets.pets[24001].node.position=Vector3(0,0,40)
	w.is_night=false;w.clock+=1;w.progression.upgrade_defense(1,1,1)
	for stroke in 8:w.clock+=.8;w.construction.work(1,1)
	check(d.level==2 and d.max_hp==1980 and parts.tier2.visible,"paid hand-built upgrade raises health and reveals authored reinforcement")
	await capture("upgrade_game")
	w.select_build(10);w.hud._update_work_panels(p)
	check(w.hud.build_cards[10].visible and not w.hud.build_cards[0].visible,"page two shows gatehouse without overlapping earlier build cards")
	w.select_build_slot(0);check(w.selected_build==10,"page-two numeric slot selects gatehouse")
	w.cycle_build(1);check(w.selected_build==0,"mouse-wheel selection wraps across both pages")
	w.select_build(10);w._update_preview();await capture("build_menu_game");w.local_build_mode=false;w.preview.hide()
	w.hud.upgrade_menu.open_nearest();await capture("settings_game");w.hud.upgrade_menu.close_panel()
	var snapshot:=w.snapshot();check(snapshot.defenses[1].gate_auto and snapshot.defenses[1].gate_open==1,"full and incremental snapshots include mechanism settings")
	var saved:=FortSave.capture(w);check(FortSave.validate(saved)=="","gatehouse and pet save validates")
	saved.defenses[1].gate_open=NAN;check(FortSave.validate(saved)!="","corrupt gate position rejected before restoring")
	var upper:Dictionary={"x":0,"z":0,"floor":1}
	check(1 in FortCastleClearance.inspect(w.castle,upper).defenses,"upper-floor expansion detects tall gatehouse for confirmed salvage")
	check(not FortPlacement.wall_overlap(location,0,"Gatehouse",location+Vector3(4.2,0,0),0,"MetalWall"),"gate and curtain wall ends touch without overlap")
	check(FortPlacement.wall_overlap(location,0,"Gatehouse",location+Vector3(0,0,1),0,"MetalWall"),"gate thickness rejects crossing wall")
	w.recv_enemy(24002,"Brute",location+Vector3.BACK*4,500)
	check(FortSiege.priority(w,w.enemies[24002])!=1,"brute does not prioritize an open gate")
	d.gate_target=0.0;d.gate_open=0.0;FortGates.pose(d)
	check(FortSiege.priority(w,w.enemies[24002])==1,"closed gate is a priority breach target")
	w.enemies[24002].node.position=location+Vector3.BACK*2;w.enemies[24002].attack=0;FortSiege.strike(w,w.enemies[24002],1);w.clock+=1;FortSiege.strike(w,w.enemies[24002],1)
	check(d.hp<d.max_hp,"telegraphed brute strike damages gatehouse")
	w.recv_enemy_dead(24002);await wait()
	var stock:int=w.shared.wood;var refund:=w.construction.salvage_refund(d);w.construction.salvage(1,1,d.work_revision)
	check(not w.defenses.has(1) and w.shared.wood==stock+refund.wood,"salvage removes gate and returns health-scaled paid resources")
	main.queue_free();await wait();print("GATE24_RESULT ","PASS" if failures==0 else "FAIL");quit(failures)
